### ISSUE TITLE
Tagging old instead of current commit

### ISSUE THREAD

**Issue by simonua** [VisualBean/VSTSTools#4] opened 2017-08-14 20:01 UTC
Hi Alex,

Great task and a nice improvement over VSTS native task! This may not be an issue with Git Tag per se, but wanted to run this by you anyway. In experimenting with your task, I see it tag an older commit, and I'm not quite sure why. Everything I see in _Get Sources_ and other tasks in the pipeline operates on the newer commit. Admittedly, I haven't dug into your source code yet to see how this could be, but wanted to throw it out here nevertheless:

![image](https://user-images.githubusercontent.com/8005145/29289275-d3eeabf0-8109-11e7-8326-bb0354bd7153.png)

Evidence of it consistently tagging old commit.

![image](https://user-images.githubusercontent.com/8005145/29289221-9b1e3b38-8109-11e7-9eed-3891690d9857.png)

**Comment by VisualBean** [comment] 2017-08-14 21:57
That is weird. I will take a look at it and see if i can make sense of it. Thanks for reaching out!

**Comment by simonua** [comment] 2017-08-14 21:59
You are welcome. Thank you for the quick follow up, Alex. Will gladly collaborate on it if I can be of assistance. It is literally the last step to my puzzle. 😀

**Comment by VisualBean** [comment] 2017-08-14 22:09
Well basically the code runs the following git commands;

Git checkout {branchname} 
Git tag {tag}
Git push origin {tag}

Is the build limited in anyway to specific commits? 
You could look at the log from the initial checkout (done by vsts)

Could you try setting debug=true and posting a screenshot again? 
Ill look more deeply into it tomorrow. Thanks

**Comment by simonua** [comment] 2017-08-15 14:19
So I took the pipeline down to just the essential tasks that I needed - getting sources, getting the package version, and tagging:

![image](https://user-images.githubusercontent.com/8005145/29317688-1eaf276e-819b-11e7-9927-57074fe61f17.png)

The log is interesting:

HEAD is at an old commit initially - the same one GitTag ends up tagging. I don't know why. Sources are set to sync (by way of not having _Don't sync sources_ checked), and everything is cleaned (not sure that matters here)

`2017-08-15T13:08:46.5572332Z HEAD is now at df62f26 Set 3.0.5`

_Get Sources_ then checks out the correct (latest) commit on _master_ (the triggering branch):

`2017-08-15T13:08:47.7831755Z HEAD is now at 0548e04... Set 3.1.4`

The _Get Version from package.json_ task then pulls the correct `3.1.4` from _package.json_. So far so good.

The _GitTag_ task alludes to the _previous_ HEAD position, but it ends up tagging df62f26 (Set 3.0.5).

`2017-08-15T13:08:51.3926672Z Previous HEAD position was 0548e04... Set 3.1.4`

```
2017-08-15T13:08:44.4133997Z ##[section]Starting: Build
2017-08-15T13:08:44.4133997Z Current agent version: '2.119.1'
2017-08-15T13:08:45.6968781Z ##[section]Starting: Initialize Job
2017-08-15T13:08:45.7281309Z Prepare build directory.
2017-08-15T13:08:45.8249343Z Set build variables.
2017-08-15T13:08:45.8249343Z Download all required tasks.
2017-08-15T13:08:45.9667205Z ##[section]Finishing: Initialize Job
2017-08-15T13:08:46.0261243Z ##[section]Starting: Get Sources
2017-08-15T13:08:46.1187663Z Syncing repository: foo-build-test (TfsGit)
2017-08-15T13:08:46.1369949Z Prepending Path environment variable with directory containing 'git.exe'.
2017-08-15T13:08:46.1500169Z ##[command]git version
2017-08-15T13:08:46.2906481Z git version 2.12.0.windows.1
2017-08-15T13:08:46.3098474Z ##[command]git config --get remote.origin.url
2017-08-15T13:08:46.4000247Z ##[command]git clean -fdx
2017-08-15T13:08:46.4475630Z ##[command]git reset --hard HEAD
2017-08-15T13:08:46.5572332Z HEAD is now at df62f26 Set 3.0.5
2017-08-15T13:08:46.5572332Z ##[command]git config gc.auto 0
2017-08-15T13:08:46.6188050Z ##[command]git config --get-all http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader
2017-08-15T13:08:46.6656909Z ##[command]git config --get-all http.proxy
2017-08-15T13:08:46.7438095Z ##[command]git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin
2017-08-15T13:08:47.6894248Z ##[command]git checkout --progress --force 0548e04d36cba4111f3db99ae8c130962a3a5235
2017-08-15T13:08:47.7675762Z Note: checking out '0548e04d36cba4111f3db99ae8c130962a3a5235'.
2017-08-15T13:08:47.7831755Z 
2017-08-15T13:08:47.7831755Z You are in 'detached HEAD' state. You can look around, make experimental
2017-08-15T13:08:47.7831755Z changes and commit them, and you can discard any commits you make in this
2017-08-15T13:08:47.7831755Z state without impacting any branches by performing another checkout.
2017-08-15T13:08:47.7831755Z 
2017-08-15T13:08:47.7831755Z If you want to create a new branch to retain commits you create, you may
2017-08-15T13:08:47.7831755Z do so (now or later) by using -b with the checkout command again. Example:
2017-08-15T13:08:47.7831755Z 
2017-08-15T13:08:47.7831755Z   git checkout -b <new-branch-name>
2017-08-15T13:08:47.7831755Z 
2017-08-15T13:08:47.7831755Z HEAD is now at 0548e04... Set 3.1.4
2017-08-15T13:08:47.7831755Z ##[command]git config http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader "AUTHORIZATION: bearer ********"
2017-08-15T13:08:47.8300517Z ##[section]Finishing: Get Sources
2017-08-15T13:08:47.8511517Z ##[section]Starting: Get Version from package.json
2017-08-15T13:08:47.8808830Z ==============================================================================
2017-08-15T13:08:47.8808830Z Task         : PowerShell
2017-08-15T13:08:47.8808830Z Description  : Run a PowerShell script
2017-08-15T13:08:47.8808830Z Version      : 1.2.3
2017-08-15T13:08:47.8808830Z Author       : Microsoft Corporation
2017-08-15T13:08:47.8808830Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2017-08-15T13:08:47.8808830Z ==============================================================================
2017-08-15T13:08:48.0498690Z ##[command]. 'D:\builds\164\s\scripts\version.ps1' 
2017-08-15T13:08:49.2207227Z 3.1.4
2017-08-15T13:08:49.2363686Z ##[section]Finishing: Get Version from package.json
2017-08-15T13:08:49.2363686Z ##[section]Starting: Tag package.json Version in Source Control
2017-08-15T13:08:49.2363686Z ==============================================================================
2017-08-15T13:08:49.2363686Z Task         : Git Tag
2017-08-15T13:08:49.2363686Z Description  : A simple task that tags a branch
2017-08-15T13:08:49.2363686Z Version      : 1.7.1
2017-08-15T13:08:49.2363686Z Author       : Alex Carlsen
2017-08-15T13:08:49.2363686Z Help         : tags the current branch with a specified tag. ### Prerequisites * Repository must be VSTS Git. * Allow scripts to access Oauth must be **Enabled** * Project Collection Build Service must have **Contribute** & **Create Tag** set to **Allow** or **Inherit Allow** for that particular repository
2017-08-15T13:08:49.2363686Z ==============================================================================
2017-08-15T13:08:51.2832868Z ##[command] git checkout master
2017-08-15T13:08:51.3926672Z Previous HEAD position was 0548e04... Set 3.1.4
2017-08-15T13:08:51.3926672Z Your branch is behind 'origin/master' by 12 commits, and can be fast-forwarded.
2017-08-15T13:08:51.4239178Z Switched to branch 'master'
2017-08-15T13:08:51.4239178Z   (use "git pull" to update your local branch)
2017-08-15T13:08:51.4239178Z ##[command] git tag  3.1.4
2017-08-15T13:08:51.4864186Z ##[command] git push origin 3.1.4
2017-08-15T13:08:56.1161167Z To https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T13:08:56.1161167Z  * [new tag]         3.1.4 -> 3.1.4
2017-08-15T13:08:56.1629664Z ##[section]Finishing: Tag package.json Version in Source Control
2017-08-15T13:08:56.1629664Z ##[section]Starting: Post Job Cleanup
2017-08-15T13:08:56.1786145Z Cleaning any cached credential from repository: foo-build-test (Git)
2017-08-15T13:08:56.1942425Z ##[command]git config --unset-all http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader
2017-08-15T13:08:56.2590374Z ##[command]git remote set-url origin https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T13:08:56.3041758Z ##[command]git remote set-url --push origin https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T13:08:56.3666462Z ##[section]Finishing: Post Job Cleanup
2017-08-15T13:08:56.3868370Z ##[section]Finishing: Build
```

**Comment by simonua** [comment] 2017-08-15 14:22
Stupid question, but why do you have to check out the current branch? Would you not expect it to already be the working branch?

```
	write-verbose "Checkout current branch."
	write-host "##[command]"git checkout $currentBranch
	git checkout $currentBranch
```

**Comment by VisualBean** [comment] 2017-08-15 16:52
Hi Simon,
Thanks a lot for the trace, ill look right into it.

Regarding the checkout, I remember it as a way to alleviate that vsts deattaches head -  which we need to reattach to tag the branch at that point in time, and checkout was the easiest way to do this :) - if you check the "get sources" log youll see a comment regarding the deattached head :)

**Comment by simonua** [comment] 2017-08-15 17:18
Hi Alex,

Yes, that's what I saw in the VSTS log as well. What you're saying makes sense to me - to alleviate what you couldn't safely account for - so that answers my most recent question. 

I ran this again in debug mode to get the verbose log. The result is the same wrong one, but it's more info. Is there any sense in pulling or does that make too much of an assertion in that the tagging should probably rely on the correct commit being available?

`git checkout $currentBranch && git pull`

```
2017-08-15T17:08:31.5158241Z ##[section]Starting: Build
2017-08-15T17:08:31.5158241Z Current agent version: '2.119.1'
2017-08-15T17:08:31.5314482Z ##[debug]Cleaning agent temp folder: D:\builds\_temp
2017-08-15T17:08:31.9524335Z ##[debug]SET TMP=D:\builds\_temp
2017-08-15T17:08:31.9524335Z ##[debug]SET TEMP=D:\builds\_temp
2017-08-15T17:08:32.8566975Z ##[section]Starting: Initialize Job
2017-08-15T17:08:32.8765766Z ##[debug]Primary repository: foo-build-test. repository type: TfsGit
2017-08-15T17:08:32.8765766Z Prepare build directory.
2017-08-15T17:08:32.9494996Z ##[debug]Delete existing artifacts directory: 'D:\builds\164\a'
2017-08-15T17:08:32.9494996Z ##[debug]Deleting artifacts directory: 'D:\builds\164\a'
2017-08-15T17:08:32.9662462Z ##[debug]Creating artifacts directory: 'D:\builds\164\a'
2017-08-15T17:08:32.9662462Z ##[debug]Delete existing test results directory: 'D:\builds\164\TestResults'
2017-08-15T17:08:32.9662462Z ##[debug]Deleting test results directory: 'D:\builds\164\TestResults'
2017-08-15T17:08:32.9662462Z ##[debug]Creating test results directory: 'D:\builds\164\TestResults'
2017-08-15T17:08:32.9662462Z ##[debug]Delete existing binaries directory: 'D:\builds\164\b'
2017-08-15T17:08:32.9662462Z ##[debug]Deleting binaries directory: 'D:\builds\164\b'
2017-08-15T17:08:32.9662462Z ##[debug]Creating binaries directory: 'D:\builds\164\b'
2017-08-15T17:08:32.9662462Z Set build variables.
2017-08-15T17:08:32.9862187Z Download all required tasks.
2017-08-15T17:08:32.9970144Z ##[debug]Task 'PowerShell' already downloaded at 'D:\builds\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\1.2.3'.
2017-08-15T17:08:32.9970144Z ##[debug]Task 'GitTag' already downloaded at 'D:\builds\_tasks\GitTag_59a7d740-450e-11e7-820e-fd60651f1ea5\1.7.1'.
2017-08-15T17:08:32.9970144Z ##[debug]Task 'Get Version from package.json' has following condition: 'succeeded()'.
2017-08-15T17:08:33.0276271Z ##[debug]Parsing expression: <succeeded()>
2017-08-15T17:08:33.0276271Z ##[debug]succeeded
2017-08-15T17:08:33.0276271Z ##[debug](
2017-08-15T17:08:33.0276271Z ##[debug])
2017-08-15T17:08:33.0467567Z ##[debug]Task 'Tag package.json Version in Source Control' has following condition: 'succeeded()'.
2017-08-15T17:08:33.0467567Z ##[debug]Parsing expression: <succeeded()>
2017-08-15T17:08:33.0467567Z ##[debug]succeeded
2017-08-15T17:08:33.0467567Z ##[debug](
2017-08-15T17:08:33.0467567Z ##[debug])
2017-08-15T17:08:33.1057556Z ##[section]Finishing: Initialize Job
2017-08-15T17:08:33.1370106Z ##[debug]Evaluating condition for step: 'Get Sources'
2017-08-15T17:08:33.1370106Z ##[debug]Evaluating: succeeded()
2017-08-15T17:08:33.1370106Z ##[debug]Evaluating succeeded:
2017-08-15T17:08:33.1550672Z ##[debug]=> (Boolean) True
2017-08-15T17:08:33.1550672Z ##[debug]Expanded: True
2017-08-15T17:08:33.1550672Z ##[debug]Result: True
2017-08-15T17:08:33.1682581Z ##[section]Starting: Get Sources
2017-08-15T17:08:33.1848376Z ##[debug]Sync source for endpoint: foo-build-test
2017-08-15T17:08:33.2463891Z Syncing repository: foo-build-test (TfsGit)
2017-08-15T17:08:33.2648381Z Prepending Path environment variable with directory containing 'git.exe'.
2017-08-15T17:08:33.2648381Z ##[debug]Path: 'C:\vsoagent\externals\git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\tools\ruby23\bin;C:\Program Files\Git\Cmd;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\tools\python2;C:\Program Files\nodejs\;C:\Users\vsoagentuser\AppData\Roaming\npm;C:\vsoagent\bin;C:\vsoagent\bin'
2017-08-15T17:08:33.2776396Z ##[debug]Get git version.
2017-08-15T17:08:33.2776396Z ##[command]git version
2017-08-15T17:08:33.4236305Z git version 2.12.0.windows.1
2017-08-15T17:08:33.4236305Z ##[debug]Detect git version: 2.12.0.
2017-08-15T17:08:33.4236305Z ##[debug]Set git useragent to: git/2.12.0 (vsts-agent-git/2.119.1).
2017-08-15T17:08:33.4338922Z ##[debug]Checking if the repo on D:\builds\164\s matches the expected repository origin URL. expected Url: https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:33.4338922Z ##[debug]Inspect remote.origin.url for repository under D:\builds\164\s
2017-08-15T17:08:33.4338922Z ##[command]git config --get remote.origin.url
2017-08-15T17:08:33.4994031Z ##[debug]Get remote origin fetch url from git config: https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:33.4994031Z ##[debug]Repository remote origin fetch url is https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:33.5120219Z ##[debug]URLs match.
2017-08-15T17:08:33.5120219Z ##[debug]Delete untracked files/folders for repository at D:\builds\164\s.
2017-08-15T17:08:33.5120219Z ##[command]git clean -fdx
2017-08-15T17:08:33.5901478Z ##[debug]Undo any changes to tracked files in the working tree for repository at D:\builds\164\s.
2017-08-15T17:08:33.5901478Z ##[command]git reset --hard HEAD
2017-08-15T17:08:33.6839013Z HEAD is now at df62f26 Set 3.0.5
2017-08-15T17:08:33.6839013Z ##[debug]Disable git auto garbage collection.
2017-08-15T17:08:33.6839013Z ##[command]git config gc.auto 0
2017-08-15T17:08:33.7620916Z ##[debug]Checking git config http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader exist or not
2017-08-15T17:08:33.7620916Z ##[command]git config --get-all http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader
2017-08-15T17:08:33.8089360Z ##[debug]Checking git config http.proxy exist or not
2017-08-15T17:08:33.8089360Z ##[command]git config --get-all http.proxy
2017-08-15T17:08:33.8557833Z ##[debug]Fetch git repository at: D:\builds\164\s remote: origin.
2017-08-15T17:08:33.8756597Z ##[command]git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin
2017-08-15T17:08:34.8669930Z remote: Microsoft (R) Visual Studio (R) Team Services        
2017-08-15T17:08:34.8669930Z remote: We noticed you're using an older version of Git. For the best experience, upgrade to a newer version.        
2017-08-15T17:08:34.8669930Z remote: 
2017-08-15T17:08:34.8669930Z remote: Found 8 objects to send. (6 ms)        
2017-08-15T17:08:34.9294701Z From https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:34.9294701Z    0548e04..4926911  master     -> origin/master
2017-08-15T17:08:34.9294701Z  * [new tag]         3.1.5      -> 3.1.5
2017-08-15T17:08:34.9607442Z ##[debug]Checkout 49269110886ad856467f00f381b04a5c9beb0860.
2017-08-15T17:08:34.9607442Z ##[command]git checkout --progress --force 49269110886ad856467f00f381b04a5c9beb0860
2017-08-15T17:08:35.0545216Z Note: checking out '49269110886ad856467f00f381b04a5c9beb0860'.
2017-08-15T17:08:35.0545216Z 
2017-08-15T17:08:35.0545216Z You are in 'detached HEAD' state. You can look around, make experimental
2017-08-15T17:08:35.0545216Z changes and commit them, and you can discard any commits you make in this
2017-08-15T17:08:35.0545216Z state without impacting any branches by performing another checkout.
2017-08-15T17:08:35.0545216Z 
2017-08-15T17:08:35.0545216Z If you want to create a new branch to retain commits you create, you may
2017-08-15T17:08:35.0545216Z do so (now or later) by using -b with the checkout command again. Example:
2017-08-15T17:08:35.0545216Z 
2017-08-15T17:08:35.0545216Z   git checkout -b <new-branch-name>
2017-08-15T17:08:35.0545216Z 
2017-08-15T17:08:35.0545216Z HEAD is now at 4926911... Set 3.1.6
2017-08-15T17:08:35.0545216Z ##[debug]Set git config http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader "AUTHORIZATION: bearer ********"
2017-08-15T17:08:35.0545216Z ##[command]git config http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader "AUTHORIZATION: bearer ********"
2017-08-15T17:08:35.1169859Z ##[section]Finishing: Get Sources
2017-08-15T17:08:35.1326291Z ##[debug]Evaluating condition for step: 'Get Version from package.json'
2017-08-15T17:08:35.1326291Z ##[debug]Evaluating: succeeded()
2017-08-15T17:08:35.1326291Z ##[debug]Evaluating succeeded:
2017-08-15T17:08:35.1326291Z ##[debug]=> (Boolean) True
2017-08-15T17:08:35.1326291Z ##[debug]Expanded: True
2017-08-15T17:08:35.1326291Z ##[debug]Result: True
2017-08-15T17:08:35.1326291Z ##[section]Starting: Get Version from package.json
2017-08-15T17:08:35.1638771Z ==============================================================================
2017-08-15T17:08:35.1638771Z Task         : PowerShell
2017-08-15T17:08:35.1638771Z Description  : Run a PowerShell script
2017-08-15T17:08:35.1638771Z Version      : 1.2.3
2017-08-15T17:08:35.1638771Z Author       : Microsoft Corporation
2017-08-15T17:08:35.1638771Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2017-08-15T17:08:35.1638771Z ==============================================================================
2017-08-15T17:08:35.3045098Z ##[debug]Working directory: 'D:\builds\164\s'
2017-08-15T17:08:35.3045098Z ##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "try { $null = [System.Security.Cryptography.ProtectedData] } catch { Write-Verbose 'Adding assemly: System.Security' ; Add-Type -AssemblyName 'System.Security' ; $null = [System.Security.Cryptography.ProtectedData] ; $Error.Clear() } ; Invoke-Expression -Command ([System.Text.Encoding]::UTF8.GetString([System.Security.Cryptography.ProtectedData]::Unprotect([System.Convert]::FromBase64String('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAATqrGjnvOk2ESjJve/9B/gAAAAACAAAAAAAQZgAAAAEAACAAAADXM62N/+I3v+h88pSvkaa+IIb7wLAJE9Q+crizxYc0NgAAAAAOgAAAAAIAACAAAAAcyu/N6M884sdYl4GMfIDDyEw4+ChS2OQqc5sQ3oHAojAAAADRQAyhud/fkrQnkK4Xrnf1uyXqqAWLdy+RZzRDEqb3Te71x1+n86TC+san3/pL51BAAAAAOmXeWQ8dD5X70tOCNR4pxE73LLPMOB/zS9y37U7vLoAVhe4wUOzSTErxGavxU5akkEi0KHci8640yN0ueuCmWg=='), [System.Convert]::FromBase64String('jFCGVSQqMo9lqQ1mjHBgdA=='), [System.Security.Cryptography.DataProtectionScope]::CurrentUser))) ; if (!(Test-Path -LiteralPath variable:\LastExitCode)) { Write-Verbose 'Last exit code is not set.' } else { Write-Verbose ('$LastExitCode: {0}' -f $LastExitCode) ; exit $LastExitCode }"
2017-08-15T17:08:35.3045098Z ##[command]. 'D:\builds\164\s\scripts\version.ps1' 
2017-08-15T17:08:36.4177132Z 3.1.6
2017-08-15T17:08:36.4295288Z ##[debug]Processed: ##vso[task.setvariable variable=PackageVersion;]3.1.6
2017-08-15T17:08:36.4607829Z ##[section]Finishing: Get Version from package.json
2017-08-15T17:08:36.4607829Z ##[debug]Evaluating condition for step: 'Tag package.json Version in Source Control'
2017-08-15T17:08:36.4607829Z ##[debug]Evaluating: succeeded()
2017-08-15T17:08:36.4607829Z ##[debug]Evaluating succeeded:
2017-08-15T17:08:36.4607829Z ##[debug]=> (Boolean) True
2017-08-15T17:08:36.4607829Z ##[debug]Expanded: True
2017-08-15T17:08:36.4607829Z ##[debug]Result: True
2017-08-15T17:08:36.4607829Z ##[section]Starting: Tag package.json Version in Source Control
2017-08-15T17:08:36.4607829Z ==============================================================================
2017-08-15T17:08:36.4607829Z Task         : Git Tag
2017-08-15T17:08:36.4607829Z Description  : A simple task that tags a branch
2017-08-15T17:08:36.4607829Z Version      : 1.7.1
2017-08-15T17:08:36.4607829Z Author       : Alex Carlsen
2017-08-15T17:08:36.4607829Z Help         : tags the current branch with a specified tag. ### Prerequisites * Repository must be VSTS Git. * Allow scripts to access Oauth must be **Enabled** * Project Collection Build Service must have **Contribute** & **Create Tag** set to **Allow** or **Inherit Allow** for that particular repository
2017-08-15T17:08:36.4607829Z ==============================================================================
2017-08-15T17:08:38.4140030Z ##[debug]VstsTaskSdk 0.8.1 commit 
2017-08-15T17:08:38.6327632Z ##[debug]INPUT_TAG: '3.1.6'
2017-08-15T17:08:38.6483894Z ##[debug]INPUT_FORCETAGCREATION: 'false'
2017-08-15T17:08:38.6796649Z ##[debug]Entering D:\builds\_tasks\GitTag_59a7d740-450e-11e7-820e-fd60651f1ea5\1.7.1\tagging.ps1.
2017-08-15T17:08:38.7264917Z ##[debug]Setting working directory to 'D:\builds\164\s'.
2017-08-15T17:08:38.7264917Z ##[debug]Checkout current branch.
2017-08-15T17:08:38.7264917Z ##[command] git checkout master
2017-08-15T17:08:38.8088401Z Previous HEAD position was 4926911... Set 3.1.6
2017-08-15T17:08:38.8088401Z Your branch is behind 'origin/master' by 14 commits, and can be fast-forwarded.
2017-08-15T17:08:38.8088401Z Switched to branch 'master'
2017-08-15T17:08:38.8088401Z   (use "git pull" to update your local branch)
2017-08-15T17:08:38.8202453Z ##[debug]Tagging 'master' with '3.1.6'.
2017-08-15T17:08:38.8202453Z ##[command] git tag  3.1.6
2017-08-15T17:08:38.8725390Z ##[debug]Push tag to origin
2017-08-15T17:08:38.8725390Z ##[command] git push origin 3.1.6
2017-08-15T17:08:39.7984587Z To https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:39.7984587Z  * [new tag]         3.1.6 -> 3.1.6
2017-08-15T17:08:39.8172418Z ##[debug]Leaving D:\builds\_tasks\GitTag_59a7d740-450e-11e7-820e-fd60651f1ea5\1.7.1\tagging.ps1.
2017-08-15T17:08:39.8609590Z ##[section]Finishing: Tag package.json Version in Source Control
2017-08-15T17:08:39.8609590Z ##[debug]Evaluating condition for step: 'Post Job Cleanup'
2017-08-15T17:08:39.8609590Z ##[debug]Always run post-job step: 'Post Job Cleanup'
2017-08-15T17:08:39.8609590Z ##[section]Starting: Post Job Cleanup
2017-08-15T17:08:39.8609590Z Cleaning any cached credential from repository: foo-build-test (Git)
2017-08-15T17:08:39.8609590Z ##[debug]Repository url=https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:39.8609590Z ##[debug]targetPath=D:\builds\164\s
2017-08-15T17:08:39.8609590Z ##[debug]Remove any extraheader and proxy setting from git config.
2017-08-15T17:08:39.8766082Z ##[debug]Unset git config --unset-all http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader
2017-08-15T17:08:39.8766082Z ##[command]git config --unset-all http.https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test.extraheader
2017-08-15T17:08:39.9234911Z ##[debug]Remove injected credential from git remote fetch url.
2017-08-15T17:08:39.9391135Z ##[debug]Set git fetch url to: https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test for remote: origin.
2017-08-15T17:08:39.9391135Z ##[command]git remote set-url origin https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:40.0017117Z ##[debug]Remove injected credential from git remote push url.
2017-08-15T17:08:40.0017117Z ##[debug]Set git push url to: https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test for remote: origin.
2017-08-15T17:08:40.0017117Z ##[command]git remote set-url --push origin https://foo.visualstudio.com/EnterpriseSoftwarePortfolio/_git/foo-build-test
2017-08-15T17:08:40.0666797Z ##[section]Finishing: Post Job Cleanup
2017-08-15T17:08:40.0797496Z ##[debug]Cleaning agent temp folder: D:\builds\_temp
2017-08-15T17:08:40.0797496Z ##[section]Finishing: Build
```

**Comment by VisualBean** [comment] 2017-08-15 17:53
The reason i am not pulling at the moment is so you can run the tag back in time, say you want to build an older version or similar. 

Ill see if i cant reproduce the issue on my vsts instance and get back to you :) - its weird that it is consistently behind.

**Comment by simonua** [comment] 2017-08-15 17:55
Yeah, you're right on with the pull. That's entirely too much assertion outside the responsibilities of GitTag. I'm thinking the trouble really is with _Get Sources_ somewhere...

**Comment by VisualBean** [comment] 2017-08-15 18:14
could you try and add a powershell script like the following
![image](https://user-images.githubusercontent.com/5294032/29329400-11076742-81f6-11e7-9529-97122c81a645.png)

check the output and tell me which commit has the Id :) - maybe even one before the tag and one after. :) that would be extremely helpful. 
Also, do you have anything special set in options / variables / retention(under settings (checkboxes in the bottom))?

Thanks alot for your patience :)

**Comment by simonua** [comment] 2017-08-15 18:15
Something in the build def got whacky, I _think_. I ended up following this:

_On the variables tab create or modify the `Build.Clean` variable and set it to `source`._
-- https://www.visualstudio.com/en-us/docs/build/scripts/git-commands

Somehow, my _Clean_ and _Clean options_ were then reset to false and hidden, but I know that I had _Clean_ set to `true` and _Clean options_ set to `Sources and output directory` initially. It was the first thing I checked after I experienced issues. I'm feeling a little stumped/dumb right now...

I'll test this a bit more, but right not it's tagging correctly. My apologies for the noise, Alex.

**Comment by VisualBean** [comment] 2017-08-15 18:16
It's really no trouble :) 

I am glad that it, atleast seems, to be solved :) 🙌

**Comment by simonua** [comment] 2017-08-15 20:16
Still some weird things going on, but I think it's really more so on the native VSTS task side than with GitTag. I'll close this, and if I come across anything definitive for GitTag, I'll reopen. Thanks so much for the help and support, Alex!

**Comment by simonua** [comment] 2017-08-15 20:31
@VisualBean, you know, I was thinking a bit more about [your comment above](https://github.com/VisualBean/VSTSTools/issues/4#issuecomment-322523659). You don't have to be in an attached head situation; you can tag whatever commit is your current working copy. Is there sense in a flag that can be set in the build step to choose _not_ to check out the current branch and instead remain on whatever commit is present in the pipeline? I wonder if that could help the issue I am seeing.

**Comment by VisualBean** [comment] 2017-08-15 20:43
Good thinking.

Ill do that tomorrow :) ill insert a flag that just as you describe :)

**Comment by simonua** [comment] 2017-08-15 20:45
Awesome! Thank you!

**Comment by simonua** [comment] 2017-08-17 03:44
@VisualBean, I copied your script and modified it to test out the removal of the branch checkout. This is crude and not well-written, but it is effective and should convey the idea. It makes assumptions about the state of the branch and basically takes a "hands-off" approach and just act on whatever is checked out (as I think it actually should since it's not _Git Tag_'s responsibility to figure that out IMHO).

```Powershell
#Adapted from Alex Carlsen: https://github.com/VisualBean/VSTSTools/blob/master/GitTag/GitTag/tagging.ps1
#This script does not check out a current branch or commit. Rather, it assumes the already-checked out commit for the tagging (i.e. the script defers all responsibility)

$workingDir = $env:SYSTEM_DEFAULTWORKINGDIRECTORY
$tag = $env:PackageVersion

if (!($env:SYSTEM_ACCESSTOKEN )) {
    throw ("OAuth token not found. Make sure to have 'Allow Scripts to Access OAuth Token' enabled in the build definition.
			Also, give 'Project Collection Build Service' 'Contribute' and 'Create Tag' permissions - Cog -> Version Control -> {Select Repository/ies}")
}

# For more information on the VSTS Task SDK:
# https://github.com/Microsoft/vsts-task-lib
write-verbose "Setting working directory to '$workingDir'."
Set-Location $workingDir

write-verbose "Tagging with '$tag'."
write-host "##[command]"git tag $tag
$errorMsg = git tag $tag 2>&1

if ($LastExitCode -ne 0 -and $errorMsg)  {
    write-error $errorMsg
}

write-verbose "Push tag to origin"
write-host "##[command]"git push origin $tag
$errorMsg = git push origin $tag 2>&1

if ($LastExitCode -ne 0 -and $errorMsg)  {
    write-error $errorMsg
}
```

![image](https://user-images.githubusercontent.com/8005145/29395108-9cb8563e-82dc-11e7-9a2e-e95779a4d72c.png)

Tags now line up with commits.
![image](https://user-images.githubusercontent.com/8005145/29395118-b24abb4a-82dc-11e7-935f-7d2655507add.png)

**Comment by VisualBean** [comment] 2017-08-17 05:12
Thats great! You are absolutely right. It should use the checked out commit! - could  you test running an old commit? - and if it works as intended maybe create a pull request - so others can see your contibution? If not ill incorporate it later today :) - great work!

**Comment by simonua** [comment] 2017-08-17 13:45
Hi @VisualBean,
I verified there is no problem on tagging the older commit. I simply queued a build with said older commit and observed it be tagged appropriately. PR is on the way, and I will reference this issue.

**Comment by VisualBean** [comment] 2017-08-18 05:37
merged with https://github.com/VisualBean/VSTSTools/pull/6 
Ill be uploading the task in a few minutes - itll be part in version 2 :)

**Closed by VisualBean** 2017-08-18 05:37 UTC

**Comment by simonua** [comment] 2017-08-18 12:17
Same to you, Alex! I appreciate the collaboration. I'm out for vacation now and next week but will check it out when I get back. If anything turns up, I'll let you know. 
All the best, 
Simon
